### ISSUE TITLE
Problems installing via npm, ENOENT, dist/index.js

### ISSUE THREAD

**Issue by cymerrad** [Perryvw/TypescriptToLua#195] opened 2018-09-18 13:18 UTC
Hi
I'm having a problem installing the transpiler via npm.

## What I did:
```
sudo npm install -g typescript-to-lua
```

## What I expected to happen:
Successful installation

## What happened instead
```
npm ERR! path /usr/lib/node_modules/typescript-to-lua/dist/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/typescript-to-lua/dist/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/radoslaw/.npm/_logs/2018-09-18T13_01_23_621Z-debug.log
```
Tail of aforementioned log:
```
1255 silly build typescript-to-lua@0.7.0
1256 info linkStuff typescript-to-lua@0.7.0
1257 silly linkStuff typescript-to-lua@0.7.0 has /usr/lib/node_modules as its parent node_modules
1258 silly linkStuff typescript-to-lua@0.7.0 is part of a global install
1259 silly linkStuff typescript-to-lua@0.7.0 is installed into a global node_modules
1260 silly linkStuff typescript-to-lua@0.7.0 is installed into the top-level global node_modules
1261 verbose linkBins [ { tstl: './dist/index.js' }, '/usr/bin', true ]
1262 timing action:build Completed in 12ms
1263 verbose unlock done using /home/radoslaw/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
1264 timing stage:rollbackFailedOptional Completed in 34ms
1265 timing stage:runTopLevelLifecycles Completed in 1716ms
1266 verbose stack Error: ENOENT: no such file or directory, chmod '/usr/lib/node_modules/typescript-to-lua/dist/index.js'
1267 verbose cwd /home/radoslaw/Documents/nakama/lua-logic-ts
1268 verbose Linux 4.15.0-33-generic
1269 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "typescript-to-lua"
1270 verbose node v10.10.0
1271 verbose npm  v6.4.1
1272 error path /usr/lib/node_modules/typescript-to-lua/dist/index.js
1273 error code ENOENT
1274 error errno -2
1275 error syscall chmod
1276 error enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/typescript-to-lua/dist/index.js'
1277 error enoent This is related to npm not being able to find a file.
1278 verbose exit [ -2, true ]
```

Installing it locally doesn't help - it fails with the same error (up to location of node_modules in my project)  

## What is my environment like
Ubuntu 16.04, npm 6.4.1, node 10.10.0

## What I've tried doing besides that
1. Installing locally (mentioned)
1. Installing tsc, node-ts globally and retrying installation
1. Cloning the repo and building from source, which went OK. Unfortunately I don't know what to do next to get a binary or a script, that will act as a transpiler.

**Comment by Perryvw** [comment] 2018-09-18 18:32
What files do you find in `/usr/lib/node_modules/typescript-to-lua/dist/`?

**Comment by cymerrad** [comment] 2018-09-19 08:47
Freshly reproduced:
```
radoslaw@kedar:~/Documents/node$ mkdir tstl-issue
radoslaw@kedar:~/Documents/node$ cd tstl-issue/
radoslaw@kedar:~/Documents/node/tstl-issue$ npm init -y
Wrote to /home/radoslaw/Documents/node/tstl-issue/package.json:

{
  "name": "tstl-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


radoslaw@kedar:~/Documents/node/tstl-issue$ npm i -D typescript-to-lua
npm WARN tstl-issue@1.0.0 No description
npm WARN tstl-issue@1.0.0 No repository field.

npm ERR! path /home/radoslaw/Documents/node/tstl-issue/node_modules/typescript-to-lua/dist/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/radoslaw/Documents/node/tstl-issue/node_modules/typescript-to-lua/dist/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/radoslaw/.npm/_logs/2018-09-19T08_27_29_464Z-debug.log
radoslaw@kedar:~/Documents/node/tstl-issue$ ls
node_modules  package.json
radoslaw@kedar:~/Documents/node/tstl-issue$ ls node_modules/.bin/
tsc       tsserver  which     
radoslaw@kedar:~/Documents/node/tstl-issue$ ls node_modules/
```
... and for a global installation:
```
radoslaw@kedar:~/Documents/node/tstl-issue$ sudo npm i -g typescript-to-lua
npm ERR! path /usr/lib/node_modules/typescript-to-lua/dist/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/typescript-to-lua/dist/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/radoslaw/.npm/_logs/2018-09-19T08_30_59_272Z-debug.log
radoslaw@kedar:~/Documents/node/tstl-issue$ ls /usr/lib/node_modules/t*
ls: cannot access '/usr/lib/node_modules/t*': No such file or directory
radoslaw@kedar:~/Documents/node/tstl-issue$ 
```

So the answer is: there are no files at all. npm rolls back after some kind of failure.  

Btw, I tried using yarn instead of npm. It successfully downloads package + dependencies, does some stuff with no errors, but doesn't link the binary - that's the only symptom. After checking node_modules, we can see there are files missing, when compared to built-by-hand package.
```
radoslaw@kedar:~/Documents/node/tstl-issue$ yarn add typescript-to-lua
   ... nothing interesting ...
radoslaw@kedar:~/Documents/node/tstl-issue$ ls node_modules/typescript-to-lua/dist/
CommandLineParser.js  Compiler.js           Index.js              lualib/               targets/              Transpiler.js         TSHelper.js
```
vs
```
radoslaw@kedar:~$ ls Documents/node/TypescriptToLua/dist/
CommandLineParser.js  CommandLineParser.js.map  Compiler.js  Compiler.js.map  Decorator.js  Decorator.js.map  Errors.js  Errors.js.map  index.js  index.js.map  lualib  targets  Transpiler.js  Transpiler.js.map  TSHelper.js  TSHelper.js.map
```

**Comment by lolleko** [comment] 2018-09-20 10:21
I don't think there are file missing with your yarn installation `Error.ts` and `Decorator.ts` are missing because they don't exists in version 0.7.0 yet, which is the version you downloaded via yarn.

We can't reproduce this issue, seems to be a problem with your npm client.

Maybe check the complete log see if you can find more info:

```
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/radoslaw/.npm/_logs/2018-09-19T08_27_29_464Z-debug.log
```

**Comment by lolleko** [comment] 2018-09-20 10:34
Sorry didn't see the posted log in your first post. Doest look like there is any more info in there.

Actually I think I know why the issue is caused. npm is trying to link `index.js` but in version 0.7.0
the index file is still called `Index.js`. Maybe linux npm handles paths differently or you have multiple versions cached somehow try: `npm cache clean --force`.

Chances are that this will also be fixed by the next update because we renamed `index.js`.

**Comment by gakada** [comment] 2018-09-20 11:00
I also had this problem (must be Linux thing as names are case-sensitive).

https://registry.npmjs.org/typescript-to-lua/-/typescript-to-lua-0.7.0.tgz has `Index.js` in `dist` capitalized.

https://github.com/Perryvw/TypescriptToLua/commit/d1f86b5f7036c38687a72550c41b00f38b95d41e is later than https://github.com/Perryvw/TypescriptToLua/commit/a864f8eaf2dd7e50c70fb5da453b9edfe8f02065, so it will need a release for that to be fixed.

**Comment by Perryvw** [comment] 2018-09-20 11:02
We'll try to release new changes today to fix this, that should probably have been done a while ago.

**Comment by Perryvw** [comment] 2018-09-20 19:15
I just released 0.8.0 please let me know if this fixed your problem.

**Comment by cymerrad** [comment] 2018-09-21 07:57
Works.
Global installation (`npm i -g ... `) fails, however. It is definitely of less importance, though, and I consider the problem fixed. Issue can be closed now.  

Btw, I'm going to rely on tstl heavily in coming weeks, and I've already found some irritating bugs, like tstl ignoring tstl-specific fields in tsconfig.json or that decorator `!TupleReturn` doesn't work on class methods. Would you care if I sent you a PR some day?  
I've never done that before and this would pop my cherry :blush:

**Comment by Perryvw** [comment] 2018-09-21 08:01
The tstl tsconfig issues should be fixed with the last PR ([changelog here](https://github.com/Perryvw/TypescriptToLua/blob/master/CHANGELOG.md)), would be nice if you can try that again.

Other than that all PRs are welcome!

**Comment by lolleko** [comment] 2018-09-21 08:02
And some tsconfig options are just nor supported. More details on limitations can be found here https://github.com/Perryvw/TypescriptToLua/wiki/Limitations

**Closed by Perryvw** 2018-09-21 08:01 UTC

**Comment by gakada** [comment] 2018-09-21 21:26
`npm i -g typescript-to-lua` works for me as well now, just need to delete symlink `/usr/lib/node_modules/typescript-to-lua` (left after using `npm i -g` in the repo).
